---
- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: krb5-user
    state: present
    cache_valid_time: 1800

- name: Set nisdomainname
  become: true
  ansible.posix.sysctl:
    name: kernel.domainname
    value: "{{ kerberos_realm }}"
    sysctl_file: /etc/sysctl.d/ansible_kerberos.conf
    reload: true
    state: present

- name: Generate krb5.conf
  become: true
  ansible.builtin.template:
    src: etc_krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart SSSD
