---
# this is a dummy task to be able to notify the "restart sssd" handler
# even when this role is used without "ldap_auth"
- name: Restart SSSD (dummy)
  ansible.builtin.command: /bin/true
  changed_when: false
  listen: "restart sssd"
